/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface WdEditor {}
  interface WdEditorAttributes extends StencilHTMLAttributes {
    'onOutput'?: (event: CustomEvent) => void;
    'onUndoStatus'?: (event: CustomEvent) => void;
  }

  interface WdToolbar {}
  interface WdToolbarAttributes extends StencilHTMLAttributes {
    'onToolbarAction'?: (event: CustomEvent) => void;
  }

  interface WriteDown {}
  interface WriteDownAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'WdEditor': Components.WdEditor;
    'WdToolbar': Components.WdToolbar;
    'WriteDown': Components.WriteDown;
  }

  interface StencilIntrinsicElements {
    'wd-editor': Components.WdEditorAttributes;
    'wd-toolbar': Components.WdToolbarAttributes;
    'write-down': Components.WriteDownAttributes;
  }


  interface HTMLWdEditorElement extends Components.WdEditor, HTMLStencilElement {}
  var HTMLWdEditorElement: {
    prototype: HTMLWdEditorElement;
    new (): HTMLWdEditorElement;
  };

  interface HTMLWdToolbarElement extends Components.WdToolbar, HTMLStencilElement {}
  var HTMLWdToolbarElement: {
    prototype: HTMLWdToolbarElement;
    new (): HTMLWdToolbarElement;
  };

  interface HTMLWriteDownElement extends Components.WriteDown, HTMLStencilElement {}
  var HTMLWriteDownElement: {
    prototype: HTMLWriteDownElement;
    new (): HTMLWriteDownElement;
  };

  interface HTMLElementTagNameMap {
    'wd-editor': HTMLWdEditorElement
    'wd-toolbar': HTMLWdToolbarElement
    'write-down': HTMLWriteDownElement
  }

  interface ElementTagNameMap {
    'wd-editor': HTMLWdEditorElement;
    'wd-toolbar': HTMLWdToolbarElement;
    'write-down': HTMLWriteDownElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
